---
- name: Collect backup config
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: no

  vars:
    wait_time: 60
    log_dir: ./log/ansible

  vars_files:
    - secrets.yml

  tasks:
    - name: Create local configs directory
      delegate_to: localhost
      run_once: true
      file:
        path: backups
        state: directory

    - name: Execute show running-config
      cisco.iosxr.iosxr_command:
        commands:
          - show running-config
      register: config_output

    - name: Save config to file
      ansible.builtin.copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "{{ playbook_dir }}/backups/{{ inventory_hostname }}.conf"
      delegate_to: localhost
