[core]
CORE-ROUTER ansible_host=172.50.50.50

[edge]
EDGE-A ansible_host=172.50.50.30
EDGE-B ansible_host=172.50.50.40

[isp]
ISP-A ansible_host=172.50.50.10
ISP-B ansible_host=172.50.50.20

[all:vars]
; ansible_connection=netconf                            # OR network_cli
; ansible_network_os=junipernetworks.junos.junos      # Mandatory for junipernetworks.junos collection (read the documentation)
