[amer]
R1 ansible_host=172.60.60.10
R2 ansible_host=172.50.50.20
R3 ansible_host=172.50.50.30

[emea]
R4 ansible_host=172.60.60.40

[apac]
R5 ansible_host=172.60.60.50
R6 ansible_host=172.60.60.60

[all:vars]
; ansible_connection=netconf                            # Global for every play
ansible_network_os=junipernetworks.junos.junos          # Used for junipernetworks.junos collection (as per documentation)
