---
- name: Interactive Junos Show Command
  hosts: all
  connection: juniper.device.pyez       # Use ansible.netcommon.netconf module for: junipernetworks.junos.junos
  gather_facts: no

  vars_prompt:
    - name: user
      prompt: Enter username
      private: false

    - name: passwd
      prompt: Enter password
      private: true

    - name: user_show_command
      prompt: "Enter the Junos show command (e.g., show version)"
      private: no
      default: "show version"

  vars:
    wait_time: 60
    log_dir: ./log/ansible

  vars_files:
    - secrets.yml

  tasks:
    - name: Create logs debug directory
      delegate_to: localhost
      run_once: true
      file:
        path: logs
        state: directory

    - name: Run command on Junos devices
      juniper.device.command:
        commands: "{{ user_show_command }}"
        formats: "text"
      register: cli_response

    - name: Print command results (Beware it truncates stdout_lines!)
      ansible.builtin.debug:
        msg: "{{ cli_response.stdout_lines }}"

    - name: Save Full Output to Logs
      ansible.builtin.copy:
        content: "{{ cli_response.stdout }}"
        dest: "./logs/{{ inventory_hostname }}_{{ user_show_command | replace(' ', '_') }}.log"
      delegate_to: localhost

    - name: Logs saved
      ansible.builtin.debug:
        msg: "Full output saved to ./logs/{{ inventory_hostname }}_{{ user_show_command | replace(' ', '_') }}.log"


    # The noisy approach
    # - name: Print command output
    #   ansible.builtin.debug:
    #     msg: "{{ item }}"
    #   loop: "{{ cli_response.stdout_lines }}"
    #   loop_control:
    #     # Hides the 'item' content in the task header to keep it 'clean'
    #     label: "Line"
