---
- name: "STAGE 1: Configuration using Red Hat Collection"
  hosts: all
  connection: juniper.device.pyez         # Global for this play

  vars_files:
    - secrets.yml

  tasks:
    - name: Configure IS-IS
      juniper.device.config:
        lines: 
          - set protocols isis level-capability level-2
        comment: update isis config

    - name: Verify Adjacency
      juniper.device.command:
        commands: "show isis adjacency"
      register: isis_state

    - name: Print command results nicely
      ansible.builtin.debug:
        msg: "{{ isis_state.stdout_lines }}"

# Run on a single host with:
# ansible-playbook compare_connection.yml -l ISP-A
