---
- name: "STAGE 0: Implement P2P interfaces + Prefixes"
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: no

  vars_files:
    - ../secrets.yml

  tasks:
    - name: Load per-node static variables
      ansible.builtin.include_vars:
        file: "../node_vars/{{ inventory_hostname }}.yml"

    - name: RENDER AND PREVIEW- Show rendered P2P IPv4 configuration and save locally
      delegate_to: localhost
      block:
        - name: Save rendered template to /tmp directory
          ansible.builtin.template:
            src: "../templates/p2p_t0.j2"
            dest: "/tmp/{{ inventory_hostname }}_p2p.cfg"

        - name: Preview the rendered P2P configuration
          ansible.builtin.debug:
            msg: 
              - "#--- P2P IPv4 ({{ inventory_hostname }}) ---#"
              - "{{ lookup('file', '/tmp/{{ inventory_hostname }}_p2p.cfg').splitlines() }}"

    - name: Configure P2P IPv4, Loopbacks and Static Routes
      cisco.iosxr.iosxr_config:
        src: "/tmp/{{ inventory_hostname }}_p2p.cfg"
        comment: "Ansible: Configured P2P IPv4, Loopbacks and Prefixes"
      register: p2p_result

    - name: Display Configuration Changes
      ansible.builtin.debug:
        var: p2p_result.commands
      # Only show the debug if commands were actually pushed
      when: p2p_result.changed

# Sanity check
# ansible R2 -i inventory.ini -e "@node_vars/R2.yml" -m debug -a "var=interfaces"
# ansible emea -m debug -a "var=hostvars[inventory_hostname]"

# Source Link:
# https://www.juniper.net/documentation/us/en/software/junos-ansible/ansible/topics/topic-map/junos-ansible-configuration-retrieving.html
