---
- name: "STAGE 0: Implement P2P interfaces + Prefixes"
  hosts: all
  connection: juniper.device.pyez
  gather_facts: no

  vars_files:
    - ../secrets.yml

  tasks:
    - name: Load per-node static variables
      ansible.builtin.include_vars:
        file: "../node_vars/{{ inventory_hostname }}.yml"

    - name: PREVIEW - Show rendered P2P IPv4 configuration
      ansible.builtin.debug:
        # Renders the template locally and splits it into a readable list
        msg: 
          - "#--- P2P IPv4 ---#"
          - "{{ lookup('template', '../templates/p2p_t0.j2').splitlines() }}"

    - name: Configure P2P IPv4, Loopbacks and Prefixes
      juniper.device.config:
        load: "set"       # Used for set-commands
        format: "set"     # Needed when using Jinja2 templates with set commands
        # The 'lookup' renders the file locally and returns a clean string
        lines: "{{ lookup('template', '../templates/p2p_t0.j2').splitlines() }}"
        comment: "Ansible: Configured P2P IPv4, Loopbacks and Prefixes"
        # ignore_warning is to accept the Junos warning gracefully if it tries to delete a config that was already removed in a previous run
        # ignore_warning: "statement not found"
        # commit: no
      register: p2p_result

    - name: Display Configuration Changes
      ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - p2p_result.diff_lines
      # Only show the debug if something actually changed
      when: p2p_result.changed

# Sanity check
# ansible R2 -i inventory.ini -e "@node_vars/R2.yml" -m debug -a "var=interfaces"
# ansible emea -m debug -a "var=hostvars[inventory_hostname]"

# Source Link:
# https://www.juniper.net/documentation/us/en/software/junos-ansible/ansible/topics/topic-map/junos-ansible-configuration-retrieving.html
