---
- name: "STAGE 1: Implement OSPF Underlay"
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: no

  vars_files:
    - ../secrets.yml

  tasks:
    - name: Load per-node static variables
      ansible.builtin.include_vars:
        file: "../node_vars/{{ inventory_hostname }}.yml"

    - name: PREVIEW - Show rendered OSPF configuration
      ansible.builtin.debug:
        # Renders the template locally and splits it into a readable list
        msg: 
          - "#--- OSPF Area ---#"
          - "{{ lookup('template', '../templates/ospf/base_t0.j2').splitlines() }}"

    - name: Configure OSPF Area
      cisco.iosxr.iosxr_config:
        src: "../templates/ospf/base_t0.j2"
        label: "Anbl_OSPF_Area"
      register: ospf_result

    - name: Display Configuration Changes
      ansible.builtin.debug:
        var: ospf_result.commands
      when: ospf_result.changed


# Sanity check
# ansible R2 -i inventory.ini -e "@node_vars/R2.yml" -m debug -a "var=interfaces"
# ansible emea -m debug -a "var=hostvars[inventory_hostname]"

# Source Link:
# https://www.juniper.net/documentation/us/en/software/junos-ansible/ansible/topics/topic-map/junos-ansible-configuration-retrieving.html
# https://www.juniper.net/documentation/us/en/software/junos-ansible/ansible/topics/topic-map/junos-ansible-commands-rpcs-executing.html
# https://galaxy.ansible.com/ui/repo/published/juniper/device/content/module/command/
# https://docs.ansible.com/ansible/latest/collections/junipernetworks/junos/junos_command_module.html#parameter-display
