---
- name: "STAGE 1: Implement OSPF Underlay"
  hosts: all
  connection: juniper.device.pyez
  gather_facts: no

  vars_files:
    - ../secrets.yml

  tasks:
    - name: Load per-node static variables
      ansible.builtin.include_vars:
        file: "../node_vars/{{ inventory_hostname }}.yml"

    - name: PREVIEW - Show rendered P2P IPv4 and OSPF configuration
      ansible.builtin.debug:
        # Renders the template locally and splits it into a readable list
        msg: 
          - "#--- P2P IPv4 ---#"
          - "{{ lookup('template', '../templates/p2p_t0.j2').splitlines() }}"
          - "#--- OSPF Area 0 ---#"
          - "{{ lookup('template', '../templates/ospf/base_t0.j2').splitlines() }}"

    - name: Configure P2P IPv4 and Loopbacks
      juniper.device.config:
        load: "set"       # Used for set-commands
        format: "set"     # Needed when using Jinja2 templates with set commands
        # The 'lookup' renders the file locally and returns a clean string
        lines: "{{ lookup('template', '../templates/p2p_t0.j2').splitlines() }}"
        comment: "Ansible: Configured P2P IPv4 and Loopbacks"
        # commit: no
      register: p2p_result

    - name: Configure OSPF Area 0
      juniper.device.config:
        load: "set"       # set performs a merge operation behind the scenes.
        format: "set"
        # We define the loopback address, router-id and ospf protocol
        # The 'lookup' renders the file locally and returns a clean string
        lines: "{{ lookup('template', '../templates/ospf/base_t0.j2').splitlines() }}"
        comment: "Ansible: Configured OSPF Area 0"
        # commit: no
      register: ospf_result

    - name: Display Configuration Changes
      ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - ospf_result.diff_lines
        - p2p_result.diff_lines
      # Only show the debug if something actually changed
      when: ospf_result.changed or p2p_result.changed

# Sanity check
# ansible R2 -i inventory.ini -e "@node_vars/R2.yml" -m debug -a "var=interfaces"
# ansible emea -m debug -a "var=hostvars[inventory_hostname]"

# Source Link:
# https://www.juniper.net/documentation/us/en/software/junos-ansible/ansible/topics/topic-map/junos-ansible-configuration-retrieving.html
