---
- name: "STAGE 2b: Implement BGP Overlay"
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: no

  vars_files:
    - ../secrets.yml

  tasks:
    - name: Load per-node static variables
      ansible.builtin.include_vars:
        file: "../node_vars/{{ inventory_hostname }}.yml"

    - name: PREPARE AND PREVIEW - Render BGP configuration and save locally
      delegate_to: localhost
      when: bgp is defined
      block:
        - name: Save rendered BGP template to /tmp directory
          ansible.builtin.template:
            src: "../templates/bgp/base_t0.j2"
            dest: "/tmp/{{ inventory_hostname }}_bgp.cfg"

        - name: Preview the rendered BGP configuration
          ansible.builtin.debug:
            msg: 
              - "#--- BGP Overlay ({{ inventory_hostname }}) ---#"
              - "{{ lookup('file', '/tmp/{{ inventory_hostname }}_bgp.cfg').splitlines() }}"

    - name: Configure BGP Settings
      cisco.iosxr.iosxr_config:
        src: "/tmp/{{ inventory_hostname }}_bgp.cfg"
        label: "Anbl_BGP_AS_{{ bgp.local_as | default('N/A') }}"
      register: bgp_result
      when: bgp is defined

    - name: Display Configuration Changes
      ansible.builtin.debug:
        var: bgp_result.commands
      when: bgp_result is defined and bgp_result.changed
